### ISSUE TITLE
[BUG] AvsInpaint hangs on higher resolutions

### ISSUE THREAD

**Issue by Purfview** [pinterf/AvsInpaint#1]
Hello Ferenc, when you'll have time, please look at it.

There is some bug with higher resolutions like 1920x1080 and AvsInpaint, if a mask is close to the left/right side then AvsInpaint hangs at start (no error).

Minimized script - bug simulator to reproduce it:

```
x=BlankClip(length=1000, width=1920, height=1080, color=$000000, pixel_type="YV12")

mask = BlankClip(x, length=1).Subtitle("Sample", text_color=$FFFFFF, x=8).Levels(180,1,181,0,255, coring=false)
# mask = BlankClip(x, length=1).Subtitle("Sample", text_color=$FFFFFF, x=519).Levels(180,1,181,0,255, coring=false) # Working position, moving the mask 1px to left("x=518") - hangs.

# x.InpaintLogo(mask, PreBlurSize=0.9, PostBlurSize=0.9)  # Droping the blur kernels to 0.9 - no hangs.
x.InpaintLogo(mask)
```

https://forum.doom9.org/showthread.php?p=1929211

**Comment by pinterf** [comment]
See link at Issue#2

**Comment by Purfview** [comment]
It's fixed.

**Comment by pinterf** [comment]
Released
https://github.com/pinterf/AvsInpaint/releases/tag/v1.3
