### ISSUE TITLE
[Feature request] Support Y8 mask

### ISSUE THREAD

**Issue by Purfview** [pinterf/AvsInpaint#2]
AvsInpaint allows "mask" in YUY2 and YV12 formats but not Y8, it looks at Y for mask and chroma is ignored, maybe it's easy fix by adding Y8 to the allowed formats.

Btw, I see you linked only to InpaintFunc, it's superseded by InpaintDelogo. :)

**Comment by pinterf** [comment]
Can you please check this one? If it's O.K. then I commit things and release.
See readme for changes.
https://drive.google.com/uc?export=download&id=1kENCQRnwWEZuYgpC3zJv0areqoQaBCVD

**Comment by Purfview** [comment]
Y8 mask works and 1080p issue is fixed too.

Thank you for being there. You are the best.
